title: SparsePainter

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Add main navigation links
main:
  - title: Introduction
    url: /
  - title: Installation
    url: /Installation.html
  - title: Usages and Parameters
    url: /Usages.html
  - title: Examples
    children:
      - title: Target-vs-Reference Painting
        url: /example/Target-vs-Reference-painting.html
      - title: Reference-vs-Reference Painting
        url: /example/Reference-vs-Reference-painting.html
      - title: All-vs-All Painting
        url: /example/All-vs-All-painting.html
