title: SparsePainter
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  # For all .md files
  - scope:
      path: "" # Matches all files
      type: "pages"
    values:
      layout: "single"

# Add main navigation links
main:
  - title: Introduction
    url: /
  - title: Installation
    url: /Installation.html
  - title: Usages and Parameters
    url: /Usages.html
  - title: Examples
    children:
      - title: Target-vs-Reference Painting
        url: /example/Target-vs-Reference-painting.html
      - title: Reference-vs-Reference Painting
        url: /example/Reference-vs-Reference-painting.html
      - title: All-vs-All Painting
        url: /example/All-vs-All-painting.html
